name: Build and test FreeIPA containers

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 4 * * 1,3,5'

env:
  TRAVIS: yes-similar-ubuntu-environment
jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-rawhide, fedora-33, fedora-32, centos-8, centos-7 ]
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t local/freeipa-server:${{ matrix.os }} -f Dockerfile.${{ matrix.os }} .
      - name: File issue if building image failed
        if: ${{ failure() && github.event_name == 'schedule' }}
        run: |
          curl -s 'https://api.github.com/repos/${{ github.repository }}/issues?labels=image-build-fail' | jq -r '.[0].state' | grep open \
          || curl -s -X POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'Accept: application/vnd.github.v3+json' \
            -d '{
              "title": "Image build for ${{ matrix.os }} failed on '$( date -I )'",
              "body": "This issue was automatically created by GitHub Action\n\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.\n",
              "labels": ["image-build-fail" ]
              }'
      - name: Create directory for artifacts
        run: mkdir freeipa-server-${{ matrix.os }}
      - name: Save image
        run: docker save local/freeipa-server:${{ matrix.os }} | gzip > freeipa-server-${{ matrix.os }}/freeipa-server-${{ matrix.os }}.tar.gz
      - name: Get FreeIPA version
        run: docker run --rm --entrypoint rpm local/freeipa-server:${{ matrix.os }} -qf --qf '%{version}\n' /usr/sbin/ipa-server-install > freeipa-server-${{ matrix.os }}/freeipa-server-${{ matrix.os }}.version
      - uses: actions/upload-artifact@v2
        with:
          name: freeipa-server-${{ matrix.os }}
          path: freeipa-server-${{ matrix.os }}

  test-docker:
    name: Run with docker
    runs-on: ubuntu-20.04
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: fedora-33
          - os: fedora-33
            readonly: --read-only
          - os: fedora-33
            readonly: --read-only
            ca: --external-ca
          - os: centos-8
          - os: centos-8
            readonly: --read-only
          - os: centos-8
            readonly: --read-only
            ca: --external-ca
          - os: centos-7
            protected_regular: unset
        os: [ fedora-32 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-${{ matrix.os }}
      - name: Load image
        run: gunzip < freeipa-server-${{ matrix.os }}.tar.gz | docker load
      - name: Install certutil
        if: ${{ matrix.ca == '--external-ca' }}
        run: sudo apt-get update -y && sudo apt-get install -y libnss3-tools
      - name: Disable fs.protected_regular
        if: ${{ matrix.protected_regular == 'unset' }}
        run: sudo sysctl fs.protected_regular=0
      - name: Run master and replica
        run: readonly=${{ matrix.readonly }} ca=${{ matrix.ca }} seccomp=${{ matrix.seccomp }} replica=${{ matrix.replica }} tests/run-master-and-replica.sh local/freeipa-server:${{ matrix.os }}
      - name: Run partial tests
        if: ${{ failure() }}
        run: tests/run-partial-tests.sh Dockerfile.${{ matrix.os }}

  test-podman:
    name: Run with sudo podman
    runs-on: ubuntu-20.04
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-33, centos-8 ]
    steps:
      - name: Install podman
        run: . /etc/os-release && echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - && sudo apt-get update -y && sudo apt-get install -y podman
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-${{ matrix.os }}
      - name: Load image
        run: gunzip < freeipa-server-${{ matrix.os }}.tar.gz | sudo podman load
      - name: Run master and replica
        run: docker='sudo podman' tests/run-master-and-replica.sh local/freeipa-server:${{ matrix.os }}
      - name: Run partial tests
        if: ${{ failure() }}
        run: docker='sudo podman' tests/run-partial-tests.sh Dockerfile.${{ matrix.os }}

  test-rootless-podman:
    name: Run with rootless podman
    runs-on: ubuntu-20.04
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-33, centos-8 ]
    steps:
      - name: Install podman and others
        run: . /etc/os-release && echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - && sudo apt-get update -y && sudo apt-get install -y podman fuse-overlayfs uidmap slirp4netns
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-${{ matrix.os }}
      - name: Load image
        run: gunzip < freeipa-server-${{ matrix.os }}.tar.gz | podman load
      - name: Enable ssh access to self
        run: ssh-keygen -f ~/.ssh/id_rsa && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 400 ~/.ssh/authorized_keys && chmod o-w ~
      - name: Run master
        shell: ssh -o StrictHostKeyChecking=no localhost bash {0}
        run: cd ${{ github.workspace }} && docker=podman replica=none tests/run-master-and-replica.sh local/freeipa-server:${{ matrix.os }} && podman ps -aq | xargs podman rm -f
      - name: Run partial tests
        if: ${{ failure() }}
        shell: ssh localhost bash {0}
        run: cd ${{ github.workspace }} && docker=podman tests/run-partial-tests.sh Dockerfile.${{ matrix.os }}

  test-upgrade:
    name: Upgrade from older version or build
    runs-on: ubuntu-20.04
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: fedora-33
            data-from: fedora-32
          - os: fedora-33
            data-from: fedora-31
          - os: fedora-32
            data-from: fedora-31
          - os: centos-8
            data-from: centos-8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-${{ matrix.os }}
      - name: Load image
        run: gunzip < freeipa-server-${{ matrix.os }}.tar.gz | docker load
      - name: Populate volume with data
        run: docker volume create loaded-data && docker create --name loaded-data -v loaded-data:/data:z docker.io/freeipa/freeipa-server:data-${{ matrix.data-from }} noop && mkdir /tmp/freeipa-data && docker run --volumes-from loaded-data -v /tmp/freeipa-data:/data-out:z --rm docker.io/library/busybox sh -c 'cd /data && cp -a . /data-out'
      - name: Run master and replica
        run: VOLUME=/tmp/freeipa-data replica=none tests/run-master-and-replica.sh local/freeipa-server:${{ matrix.os }}

  test-k3s:
    name: Run with K3s
    runs-on: ubuntu-20.04
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-33, centos-8 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-${{ matrix.os }}
      - name: Unzip the image
        run: gunzip freeipa-server-${{ matrix.os }}.tar.gz
      - name: Run K3s and master in it
        run: tests/run-master-in-k3s.sh local/freeipa-server:${{ matrix.os }} freeipa-server-${{ matrix.os }}.tar

  push-after-success-precondition:
    name: Check delivery to registries
    needs: [ test-docker, test-podman, test-rootless-podman, test-upgrade, test-k3s ]
    runs-on: ubuntu-20.04
    env:
      REGISTRY_TARGET_LIST: "${{ secrets.REGISTRY_TARGET_LIST }}"
      REGISTRY_CREDENTIALS_FILE: "${{ secrets.REGISTRY_CREDENTIALS_FILE }}"
    steps:
      - name: Check settings
        id: check
        run: |
          # Check the branch is allowed to push the image
          read -a BRANCH_LIST <<< "${REGISTRY_ALLOWED_BRANCH_LIST}"
          if [ ${#BRANCH_LIST[@]} -eq 0 ]; then
            is_branch_allowed=0
          else
            is_branch_allowed=0
            for branch in ${BRANCH_LIST[@]}; do
              [ "refs/heads/${branch}" == ${{ github.branch }} ] && {
                is_branch_allowed=1
                break
              }
            done
          fi

          # Check the credentials are filled
          if [ "${REGISTRY_CREDENTIALS_FILE}" != "" ]; then
            are_credentials_present=1
          else
            echo "REGISTRY_CREDENTIALS_FILE secret is empty or does not exist"
            are_credentials_present=0
          fi

          # Check the target list
          if [ "${REGISTRY_TARGET_LIST}" == "" ]; then
            echo "REGISTRY_TARGET_LIST secret is empty or does not exist"
            has_target_list=0
          else
            IFS=":" read -a TARGET_LIST <<< "${REGISTRY_TARGET_LIST}"
            if [ ${#TARGET_LIST[@]} -eq 0 ]; then
              echo "Check REGISTRY_TARGET_LIST secret in your repository settings"
              has_target_list=0
            else
              has_target_list=1
            fi
          fi

          # Set the output value
          if [ "${is_branch_allowed}" -eq 1 ] \
             && [ "${are_credentials_present}" -eq 1 ] \
             && [ "${has_target_list}" -eq 1 ]; then
            echo "::set-output name=is-allowed-to-push::true"
          else
            echo "::set-output name=is-allowed-to-push::false"
          fi

    outputs:
      is-allowed-to-push: ${{ steps.check.outputs.is-allowed-to-push }}

  push-after-success:
    name: Delivery images to registries
    runs-on: ubuntu-20.04
    needs: [ push-after-success-precondition ]
    if: needs.push-after-success-precondition.outputs.is-allowed-to-push == 'true' && github.event_name != 'pull_request'
    env:
      REGISTRY_TARGET_LIST: "${{ secrets.REGISTRY_TARGET_LIST }}"
    steps:
      - name: Prepare credentials
        run: |
          cat > "auth.json" << EOF
          ${{ secrets.REGISTRY_CREDENTIALS_FILE }}
          EOF
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-fedora-33
      - name: Push Fedora 33 image to the registry
        run: |
          IFS=":" read -a TARGET_LIST <<< "${REGISTRY_TARGET_LIST}"
          for base_name in "${TARGET_LIST[@]}"; do
            skopeo copy --authfile=auth.json docker-archive:freeipa-server-fedora-33.tar.gz docker://${base_name}:fedora-33
          done
      - name: Push Fedora 33 image tagged with FreeIPA version to the registry
        run: |
          IFS=":" read -a TARGET_LIST <<< "${REGISTRY_TARGET_LIST}"
          for base_name in "${TARGET_LIST[@]}"; do
            skopeo copy --authfile=auth.json docker-archive:freeipa-server-fedora-33.tar.gz docker://${base_name}:fedora-33-$( cat freeipa-server-fedora-33.version )
          done
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-fedora-32
      - name: Push Fedora 32 image to the registry
        run: |
          IFS=":" read -a TARGET_LIST <<< "${REGISTRY_TARGET_LIST}"
          for base_name in "${TARGET_LIST[@]}"; do
            skopeo copy --authfile=auth.json docker-archive:freeipa-server-fedora-32.tar.gz docker://${base_name}:fedora-32
          done
      - name: Push Fedora 32 image tagged with FreeIPA version to the registry
        run: |
          IFS=":" read -a TARGET_LIST <<< "${REGISTRY_TARGET_LIST}"
          for base_name in "${TARGET_LIST[@]}"; do
            skopeo copy --authfile=auth.json docker-archive:freeipa-server-fedora-32.tar.gz docker://${base_name}:fedora-32-$( cat freeipa-server-fedora-32.version )
          done
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-centos-8
      - name: Push CentOS 8 image to Docker Hub
        run: skopeo copy --authfile=auth.json docker-archive:freeipa-server-centos-8.tar.gz docker://docker.io/freeipa/freeipa-server:centos-8
      - name: Push CentOS 8 image tagged with FreeIPA version to Docker Hub
        run: skopeo copy --authfile=auth.json docker-archive:freeipa-server-centos-8.tar.gz docker://docker.io/freeipa/freeipa-server:centos-8-$( cat freeipa-server-centos-8.version )
      - uses: actions/download-artifact@v2
        with:
          name: freeipa-server-centos-7
      - name: Push CentOS 7 image to the registry
        run: |
          IFS=":" read -a TARGET_LIST <<< "${REGISTRY_TARGET_LIST}"
          for base_name in "${TARGET_LIST[@]}"; do
            skopeo copy --authfile=auth.json docker-archive:freeipa-server-centos-7.tar.gz docker://${base_name}:centos-7
          done
      - name: Push CentOS 7 image tagged with FreeIPA version to the registry
        run: |
          IFS=":" read -a TARGET_LIST <<< "${REGISTRY_TARGET_LIST}"
          for base_name in "${TARGET_LIST[@]}"; do
            skopeo copy --authfile=auth.json docker-archive:freeipa-server-centos-7.tar.gz docker://${base_name}:centos-7-$( cat freeipa-server-centos-7.version )
          done
